### ISSUE TITLE
"view basket" alert link/button has been lost

### ISSUE THREAD

**Issue by richjoblingdavis** [andyplak/events-manager-tickets-for-checkin-apps#11]
latest version of the EM/Woo plugin. Upon saving the settings the html for the "view basket" alert link/button has been lost

**Comment by richjoblingdavis** [comment]
@andyplak Here are where the settings have moved to in Woocommerce - https://www.quirkycampers.com/uk/wp-admin/admin.php?page=wc-settings&tab=events-manager

**Comment by richjoblingdavis** [comment]
There are 2 messages that need the basket link adding back in: (https://www.quirkycampers.com/uk/basket/)

Booking added to cart -  "Your booking has been added to the basket. [View Basket](https://www.quirkycampers.com/uk/basket/)"(button)

Booking already added - "You already have ticket(s) for this event in your basket. [View your basket](https://www.quirkycampers.com/uk/basket/) to proceed to payment or remove them."

**Comment by andyplak** [comment]
Woo admin interface is stripping out the html tags. Looking at the EM code, as these are pulled from options, I think we'll need to hook into WP core get_options to modify these:

`option_dbem_woocommerce_bookings_feedback_added`
`option_dbem_woocommerce_addtocart_added`
`dbem_woocommerce_bookings_feedback_already_added`

String replace on text "view basket" would do the job.

**Comment by andyplak** [comment]
Fixed and closed via https://github.com/andyplak/events-manager-woocommerce-quirky/issues/1
