### ISSUE TITLE
Ticket orders with Zero total - AJAX error at checkout. Order still goes through

### ISSUE THREAD

**Issue by richjoblingdavis** [andyplak/events-manager-tickets-for-checkin-apps#13]
Ticket orders with Zero total - AJAX error at checkout. Order still goes through

![image](https://github.com/andyplak/events-manager-tickets-for-checkin-apps/assets/83953130/ab1adf1e-9549-463a-96e8-72435a0b9724)

![image](https://github.com/andyplak/events-manager-tickets-for-checkin-apps/assets/83953130/2a6e8f07-fa9a-47d2-ab6b-6738d135864e)

**Comment by andyplak** [comment]
`[05-Oct-2023 21:28:13 UTC] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /home/quirkycampers.com/public_html/uk/wp-content/plugins/woocommerce-xero/includes/class-wc-xr-line-item.php:204`

**Comment by andyplak** [comment]
Fixed via https://github.com/Quirky-Campers/woocommerce-xero-qc/commit/5ef760fc50bdf7f473b02ec624da18a7fb3cdac6
