### ISSUE TITLE
Not exporting Names or emails for guest users.

### ISSUE THREAD

**Issue by richjoblingdavis** [andyplak/events-manager-tickets-for-checkin-apps#2]
Before enabling the plugin, the exporter was doing this. My guess it's pulling the wrong field from somewhere. Example file attached. Rows 2-4 should be Darren Green.[](url)

**Comment by andyplak** [comment]
I think this is actually an issue with Events Manager WooCommerce integration. Guest users are logged under a single EM Guest User account, while user data is pulled in from Woo Commerce. This works correctly in bookings list, but breaks on export.

**Comment by andyplak** [comment]
It is an issue with this plugin, as after disabling and exporting again, the data is correct.

**Comment by andyplak** [comment]
Check `buildcsv()` against EM 6.  Possibly some breaking changes in v6.
https://github.com/andyplak/events-manager-tickets-for-checkin-apps/blob/1161f084c635084892ce3b0cdb024cdb51a83f67/src/class-bookings-exporter.php#L67-L146
