### ISSUE TITLE
Not exporting the Woo "Order ID" field 

### ISSUE THREAD

**Issue by richjoblingdavis** [andyplak/events-manager-tickets-for-checkin-apps#3]
Was thinking we could use this field to assign a unique ID to each row this time. Rather than using the booking ID field

**Comment by andyplak** [comment]
This is now exported (using default EM code) but oddly contains the full HTML for a link to the order.
As discussed elsewhere, using this for the QR code for uniqueness doesn't give any advantages over the booking ID. We still need to differentiate with ticket type and and ticket type count.

**Comment by andyplak** [comment]
I've logged the wrapping of order id in a link in the csv as a bug with the Events Manager team:

This is minor, but if you're exporting the Order ID as part of the bookings csv, the order ID is included as a HTML link.

See `Events_Manager_WooCommerce\Bookings::em_bookings_table_rows_col()`

	if( $col == 'woocommerce_order_id' ){
		$value = '';
		if( !empty($EM_Booking->booking_meta['woocommerce']['order_id']) ) {
			$order = wc_get_order($EM_Booking->booking_meta['woocommerce']['order_id']);
			$admin_url = $order->get_edit_order_url();
			$value = '<a href="'. esc_url($admin_url) .'">'. $EM_Booking->booking_meta['woocommerce']['order_id'] .'</a>';
		}
	}

could be updated to this:


	if( $col == 'woocommerce_order_id' ){
		$value = '';
		if( !empty($EM_Booking->booking_meta['woocommerce']['order_id']) ) {
			if( $csv ) {
				$value = $EM_Booking->booking_meta['woocommerce']['order_id'];
			}else{
				$order = wc_get_order($EM_Booking->booking_meta['woocommerce']['order_id']);
				$admin_url = $order->get_edit_order_url();
				$value = '<a href="'. esc_url($admin_url) .'">'. $EM_Booking->booking_meta['woocommerce']['order_id'] .'</a>';
			}
		}
	}


Thus for the csv we only get the ID, while the tables get the full url.

**Comment by andyplak** [comment]
Meanwhile, I've added a fix in this plugin using the `em_bookings_table_rows_col_woocommerce_order_id` filter.
