### ISSUE TITLE
Basket not updating when adding tickets

### ISSUE THREAD

**Issue by richjoblingdavis** [andyplak/events-manager-tickets-for-checkin-apps#9]
Add ticket > "boking added to your basket" > go to basket > basket empty > refresh basket or go to another page on the website > basket updates

Other products go in fine
If I already have another product in the basket, the ticket goes in and updates fine

**Comment by andyplak** [comment]
Was related to server caching. 

> It looks like the issue is with the Redis Page Cache. I have left off for now whilst I try and figure out why this isn't being bypassed correctly.
